{
    'eleves': [
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013365017179',
         'NOTEEPRE': '18.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '1',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'ادم المزاز'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013365017179',
         'NOTEEPRE': '15.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '1',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'ادم المزاز'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013365017179',
         'NOTEEPRE': '08.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '1',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'ادم المزاز'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013390038735',
         'NOTEEPRE': '17.75',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '2',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'ادم غوفة'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013390038735',
         'NOTEEPRE': '12.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '2',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'ادم غوفة'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013390038735',
         'NOTEEPRE': '06.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '2',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'ادم غوفة'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013382046642',
         'NOTEEPRE': '14.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '3',
         'obseprof': 'متوسط',
         'prenomnom': 'اية اللجمي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013382046642',
         'NOTEEPRE': '15.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '3',
         'obseprof': 'متوسط',
         'prenomnom': 'اية اللجمي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013382046642',
         'NOTEEPRE': '05.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '3',
         'obseprof': 'متوسط',
         'prenomnom': 'اية اللجمي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '012975060914',
         'NOTEEPRE': '16.75',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '4',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد بن موسى'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '012975060914',
         'NOTEEPRE': '14.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '4',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد بن موسى'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '012975060914',
         'NOTEEPRE': '07.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '4',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد بن موسى'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013175041164',
         'NOTEEPRE': '18.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '5',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد بشار القرماني'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013175041164',
         'NOTEEPRE': '15.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '5',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد بشار القرماني'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013175041164',
         'NOTEEPRE': '04.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '5',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد بشار القرماني'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '012669030762',
         'NOTEEPRE': '17.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '6',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد امين بيوض'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '012669030762',
         'NOTEEPRE': '13.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '6',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد امين بيوض'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '012669030762',
         'NOTEEPRE': '07.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '6',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد امين بيوض'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013435035924',
         'NOTEEPRE': '19.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '7',
         'obseprof': 'حسن جدا',
         'prenomnom': 'احمد سحيمي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013435035924',
         'NOTEEPRE': '19.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '7',
         'obseprof': 'حسن جدا',
         'prenomnom': 'احمد سحيمي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013435035924',
         'NOTEEPRE': '13.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '7',
         'obseprof': 'حسن جدا',
         'prenomnom': 'احمد سحيمي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013499034605',
         'NOTEEPRE': '18.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '8',
         'obseprof': 'ممتاز',
         'prenomnom': 'احمد مبارك الترجمان'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013499034605',
         'NOTEEPRE': '17.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '8',
         'obseprof': 'ممتاز',
         'prenomnom': 'احمد مبارك الترجمان'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013499034605',
         'NOTEEPRE': '19.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '8',
         'obseprof': 'ممتاز',
         'prenomnom': 'احمد مبارك الترجمان'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013214035770',
         'NOTEEPRE': '18.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '9',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد ضياء ابراهيم'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013214035770',
         'NOTEEPRE': '10.75',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '9',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد ضياء ابراهيم'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013214035770',
         'NOTEEPRE': '08.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '9',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'احمد ضياء ابراهيم'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013214022737',
         'NOTEEPRE': '17.75',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '10',
         'obseprof': 'متوسط',
         'prenomnom': 'انس الرواتبي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013214022737',
         'NOTEEPRE': '12.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '10',
         'obseprof': 'متوسط',
         'prenomnom': 'انس الرواتبي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013214022737',
         'NOTEEPRE': '03.75',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '10',
         'obseprof': 'متوسط',
         'prenomnom': 'انس الرواتبي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013346035592',
         'NOTEEPRE': '19.75',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '11',
         'obseprof': 'حسن',
         'prenomnom': 'ايمن ماني'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013346035592',
         'NOTEEPRE': '15.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '11',
         'obseprof': 'حسن',
         'prenomnom': 'ايمن ماني'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013346035592',
         'NOTEEPRE': '12.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '11',
         'obseprof': 'حسن',
         'prenomnom': 'ايمن ماني'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013382046743',
         'NOTEEPRE': '14.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '12',
         'obseprof': 'متوسط',
         'prenomnom': 'اسراء اللجمي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013382046743',
         'NOTEEPRE': '13.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '12',
         'obseprof': 'متوسط',
         'prenomnom': 'اسراء اللجمي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013382046743',
         'NOTEEPRE': '04.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '12',
         'obseprof': 'متوسط',
         'prenomnom': 'اسراء اللجمي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013384019883',
         'NOTEEPRE': '15.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '13',
         'obseprof': 'متوسط',
         'prenomnom': 'دانية الداعي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013384019883',
         'NOTEEPRE': '11.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '13',
         'obseprof': 'متوسط',
         'prenomnom': 'دانية الداعي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013384019883',
         'NOTEEPRE': '09.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '13',
         'obseprof': 'متوسط',
         'prenomnom': 'دانية الداعي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013378024172',
         'NOTEEPRE': '06.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '14',
         'obseprof': 'دون المتوسط',
         'prenomnom': 'ريان بوغريو'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013378024172',
         'NOTEEPRE': '14.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '14',
         'obseprof': 'دون المتوسط',
         'prenomnom': 'ريان بوغريو'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013378024172',
         'NOTEEPRE': '09.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '14',
         'obseprof': 'دون المتوسط',
         'prenomnom': 'ريان بوغريو'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013349029155',
         'NOTEEPRE': '06.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '15',
         'obseprof': 'ضعيف',
         'prenomnom': 'شهد تومية'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013349029155',
         'NOTEEPRE': '11.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '15',
         'obseprof': 'ضعيف',
         'prenomnom': 'شهد تومية'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013349029155',
         'NOTEEPRE': '04.75',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '15',
         'obseprof': 'ضعيف',
         'prenomnom': 'شهد تومية'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013348045112',
         'NOTEEPRE': '18.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '16',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'عمر الخصيبي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013348045112',
         'NOTEEPRE': '13.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '16',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'عمر الخصيبي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013348045112',
         'NOTEEPRE': '07.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '16',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'عمر الخصيبي'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013357045092',
         'NOTEEPRE': '19.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '17',
         'obseprof': 'حسن',
         'prenomnom': 'عمر ابن عمر'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013357045092',
         'NOTEEPRE': '15.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '17',
         'obseprof': 'حسن',
         'prenomnom': 'عمر ابن عمر'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013357045092',
         'NOTEEPRE': '11.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '17',
         'obseprof': 'حسن',
         'prenomnom': 'عمر ابن عمر'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013262034101',
         'NOTEEPRE': '13.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '18',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'فادي عبد الله'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013262034101',
         'NOTEEPRE': '15.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '18',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'فادي عبد الله'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013262034101',
         'NOTEEPRE': '09.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '18',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'فادي عبد الله'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013267012726',
         'NOTEEPRE': '09.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '19',
         'obseprof': 'دون المتوسط',
         'prenomnom': 'محمد امين الصغير'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013267012726',
         'NOTEEPRE': '13.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '19',
         'obseprof': 'دون المتوسط',
         'prenomnom': 'محمد امين الصغير'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013267012726',
         'NOTEEPRE': '05.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '19',
         'obseprof': 'دون المتوسط',
         'prenomnom': 'محمد امين الصغير'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '012210037674',
         'NOTEEPRE': 'غ.ش.',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '20',
         'obseprof': '',
         'prenomnom': 'محمد امين قسومة'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '012210037674',
         'NOTEEPRE': 'غ.ش.',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '20',
         'obseprof': '',
         'prenomnom': 'محمد امين قسومة'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '012210037674',
         'NOTEEPRE': 'غ.ش.',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '20',
         'obseprof': '',
         'prenomnom': 'محمد امين قسومة'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013553037838',
         'NOTEEPRE': '17.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '21',
         'obseprof': 'حسن جدا',
         'prenomnom': 'محمد رايد محفوظ'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013553037838',
         'NOTEEPRE': '18.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '21',
         'obseprof': 'حسن جدا',
         'prenomnom': 'محمد رايد محفوظ'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013553037838',
         'NOTEEPRE': '17.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '21',
         'obseprof': 'حسن جدا',
         'prenomnom': 'محمد رايد محفوظ'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013184044986',
         'NOTEEPRE': 'غ.ش.',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '22',
         'obseprof': '',
         'prenomnom': 'محمد ياسين بن الفقيه'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013184044986',
         'NOTEEPRE': 'غ.ش.',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '22',
         'obseprof': '',
         'prenomnom': 'محمد ياسين بن الفقيه'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013184044986',
         'NOTEEPRE': 'غ.ش.',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '22',
         'obseprof': '',
         'prenomnom': 'محمد ياسين بن الفقيه'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '012195039555',
         'NOTEEPRE': 'غ.ش.',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '23',
         'obseprof': 'ضعيف',
         'prenomnom': 'محمد امين سهلول'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '012195039555',
         'NOTEEPRE': 'غ.ش.',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '23',
         'obseprof': 'ضعيف',
         'prenomnom': 'محمد امين سهلول'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '012195039555',
         'NOTEEPRE': '05.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '23',
         'obseprof': 'ضعيف',
         'prenomnom': 'محمد امين سهلول'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '012878006451',
         'NOTEEPRE': '11.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '24',
         'obseprof': 'دون المتوسط',
         'prenomnom': 'هاشم المهيري'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '012878006451',
         'NOTEEPRE': '13.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '24',
         'obseprof': 'دون المتوسط',
         'prenomnom': 'هاشم المهيري'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '012878006451',
         'NOTEEPRE': '05.00',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '24',
         'obseprof': 'دون المتوسط',
         'prenomnom': 'هاشم المهيري'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013419030621',
         'NOTEEPRE': '19.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '25',
         'obseprof': 'حسن جدا',
         'prenomnom': 'ياسمين يزيد'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013419030621',
         'NOTEEPRE': '18.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '25',
         'obseprof': 'حسن جدا',
         'prenomnom': 'ياسمين يزيد'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013419030621',
         'NOTEEPRE': '12.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '25',
         'obseprof': 'حسن جدا',
         'prenomnom': 'ياسمين يزيد'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'IDENELEV': '013225016069',
         'NOTEEPRE': '19.25',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية',
         'numOrdre': '26',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'يسري البامري'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'IDENELEV': '013225016069',
         'NOTEEPRE': '12.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية',
         'numOrdre': '26',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'يسري البامري'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'IDENELEV': '013225016069',
         'NOTEEPRE': '08.50',
         'NUMEEPRE': '1',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية',
         'numOrdre': '26',
         'obseprof': 'قريب من الحسن',
         'prenomnom': 'يسري البامري'}],
    'epreuves': [
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '30',
         'CODETYPEMATI': '10',
         'NOTEEPRE': '--.--',
         'NUMEEPRE': '1',
         'abretypeeprear': 'ف.م.',
         'libTypeEpr': 'فرض مــراقبة',
         'libeMat': 'إعلامية'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '32',
         'CODETYPEMATI': '10',
         'NOTEEPRE': '--.--',
         'NUMEEPRE': '1',
         'abretypeeprear': 'ع.ت.د',
         'libTypeEpr': 'عدد التقييم الدوري',
         'libeMat': 'إعلامية'},
        {'CODEETAB': '843010',
         'CODEMATI': '2001',
         'CODETYPEEPRE': '40',
         'CODETYPEMATI': '10',
         'NOTEEPRE': '--.--',
         'NUMEEPRE': '1',
         'abretypeeprear': 'ف.ت.',
         'libTypeEpr': 'فرض تأليفي',
         'libeMat': 'إعلامية'}
    ],
    'generalInfos': {
        'codeclass': '31230202',
        'codedisc': '20',
        'codedre': '84',
        'codeeetab': '843010',
        'codematiere': '2001',
        'codeperiodexam': '31',
        'drear': 'ـسوسة',
        'iuense': '0077143288',
        'libeclass': 'ثانية تكنولوجيا الإعلامية 2',
        'libedisc': 'إعلامية',
        'libeetab': 'معهد حمام سوسة',
        'libematier': 'إعلامية',
        'libens': 'محمد أنيس ماني',
        'libperiodexam': 'الثلاثي الأول',
        'nbrEleve': '26',
        'nbrclass': '2'
    }
}
