{'eleves': [
    {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013062055564',
             'NOTEEPRE': '14.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '1',
             'obseprof': 'حسن',
             'prenomnom': 'ادم بن حميدة'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013062055564',
             'NOTEEPRE': '12.25',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '1',
             'obseprof': 'حسن',
             'prenomnom': 'ادم بن حميدة'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '013062055564',
             'NOTEEPRE': '16.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '1',
             'obseprof': 'حسن',
             'prenomnom': 'ادم بن حميدة'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012974053124',
             'NOTEEPRE': '10.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '2',
             'obseprof': 'حسن',
             'prenomnom': 'ادم موقو'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012974053124',
             'NOTEEPRE': '14.00',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '2',
             'obseprof': 'حسن',
             'prenomnom': 'ادم موقو'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012974053124',
             'NOTEEPRE': '19.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '2',
             'obseprof': 'حسن',
             'prenomnom': 'ادم موقو'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012970024489',
             'NOTEEPRE': '11.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '3',
             'obseprof': 'ضعيف',
             'prenomnom': 'امل ابن مسعود'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012970024489',
             'NOTEEPRE': '04.25',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '3',
             'obseprof': 'ضعيف',
             'prenomnom': 'امل ابن مسعود'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012970024489',
             'NOTEEPRE': '07.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '3',
             'obseprof': 'ضعيف',
             'prenomnom': 'امل ابن مسعود'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013103014321',
             'NOTEEPRE': '11.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '4',
             'obseprof': 'حسن',
             'prenomnom': 'امل كريفة'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013103014321',
             'NOTEEPRE': '13.00',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '4',
             'obseprof': 'حسن',
             'prenomnom': 'امل كريفة'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '013103014321',
             'NOTEEPRE': '17.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '4',
             'obseprof': 'حسن',
             'prenomnom': 'امل كريفة'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013153036716',
             'NOTEEPRE': '11.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '5',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'ايهم الجديدي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013153036716',
             'NOTEEPRE': '15.25',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '5',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'ايهم الجديدي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '013153036716',
             'NOTEEPRE': '13.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '5',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'ايهم الجديدي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013170016564',
             'NOTEEPRE': '05.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '6',
             'obseprof': 'دون المتوسط',
             'prenomnom': 'ابرار قعلول'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013170016564',
             'NOTEEPRE': '10.25',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '6',
             'obseprof': 'دون المتوسط',
             'prenomnom': 'ابرار قعلول'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '013170016564',
             'NOTEEPRE': '09.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '6',
             'obseprof': 'دون المتوسط',
             'prenomnom': 'ابرار قعلول'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012883007611',
             'NOTEEPRE': '10.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '7',
             'obseprof': 'ضعيف',
             'prenomnom': 'احمد عبد الرحيم غماري'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012883007611',
             'NOTEEPRE': '05.50',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '7',
             'obseprof': 'ضعيف',
             'prenomnom': 'احمد عبد الرحيم غماري'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012883007611',
             'NOTEEPRE': '05.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '7',
             'obseprof': 'ضعيف',
             'prenomnom': 'احمد عبد الرحيم غماري'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012985016245',
             'NOTEEPRE': '06.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '8',
             'obseprof': 'متوسط',
             'prenomnom': 'امير الجديدي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012985016245',
             'NOTEEPRE': '17.00',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '8',
             'obseprof': 'متوسط',
             'prenomnom': 'امير الجديدي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012985016245',
             'NOTEEPRE': '09.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '8',
             'obseprof': 'متوسط',
             'prenomnom': 'امير الجديدي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012600021124',
             'NOTEEPRE': '08.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '9',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'رايد الشمسي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012600021124',
             'NOTEEPRE': '17.00',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '9',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'رايد الشمسي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012600021124',
             'NOTEEPRE': '11.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '9',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'رايد الشمسي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012303033901',
             'NOTEEPRE': '05.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '10',
             'obseprof': 'ضعيف',
             'prenomnom': 'رسلان الغرزول'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012303033901',
             'NOTEEPRE': '07.25',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '10',
             'obseprof': 'ضعيف',
             'prenomnom': 'رسلان الغرزول'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012303033901',
             'NOTEEPRE': '06.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '10',
             'obseprof': 'ضعيف',
             'prenomnom': 'رسلان الغرزول'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012930056752',
             'NOTEEPRE': '10.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '11',
             'obseprof': 'متوسط',
             'prenomnom': 'ريان المخينيني'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012930056752',
             'NOTEEPRE': '10.25',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '11',
             'obseprof': 'متوسط',
             'prenomnom': 'ريان المخينيني'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012930056752',
             'NOTEEPRE': '10.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '11',
             'obseprof': 'متوسط',
             'prenomnom': 'ريان المخينيني'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012870037596',
             'NOTEEPRE': '12.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '12',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'زينب بلخيرية'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012870037596',
             'NOTEEPRE': '09.00',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '12',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'زينب بلخيرية'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012870037596',
             'NOTEEPRE': '13.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '12',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'زينب بلخيرية'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012954039596',
             'NOTEEPRE': '13.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '13',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'صفاء زيراوي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012954039596',
             'NOTEEPRE': '11.50',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '13',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'صفاء زيراوي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012954039596',
             'NOTEEPRE': '12.25',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '13',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'صفاء زيراوي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012950018342',
             'NOTEEPRE': '18.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '14',
             'obseprof': 'حسن',
             'prenomnom': 'عثمان المهيري'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012950018342',
             'NOTEEPRE': '07.25',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '14',
             'obseprof': 'حسن',
             'prenomnom': 'عثمان المهيري'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012950018342',
             'NOTEEPRE': '15.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '14',
             'obseprof': 'حسن',
             'prenomnom': 'عثمان المهيري'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012477024215',
             'NOTEEPRE': '12.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '15',
             'obseprof': 'متوسط',
             'prenomnom': 'عمر الاخضر'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012477024215',
             'NOTEEPRE': '06.00',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '15',
             'obseprof': 'متوسط',
             'prenomnom': 'عمر الاخضر'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012477024215',
             'NOTEEPRE': '13.25',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '15',
             'obseprof': 'متوسط',
             'prenomnom': 'عمر الاخضر'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012985031403',
             'NOTEEPRE': '07.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '16',
             'obseprof': 'ضعيف',
             'prenomnom': 'فرح الحوار'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012985031403',
             'NOTEEPRE': '09.75',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '16',
             'obseprof': 'ضعيف',
             'prenomnom': 'فرح الحوار'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012985031403',
             'NOTEEPRE': '07.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '16',
             'obseprof': 'ضعيف',
             'prenomnom': 'فرح الحوار'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013016007947',
             'NOTEEPRE': '11.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '17',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'لوي طالبي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013016007947',
             'NOTEEPRE': '11.00',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '17',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'لوي طالبي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '013016007947',
             'NOTEEPRE': '15.25',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '17',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'لوي طالبي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012741047909',
             'NOTEEPRE': '04.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '18',
             'obseprof': 'ضعيف',
             'prenomnom': 'لينا بن عمر'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012741047909',
             'NOTEEPRE': '09.25',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '18',
             'obseprof': 'ضعيف',
             'prenomnom': 'لينا بن عمر'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012741047909',
             'NOTEEPRE': '08.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '18',
             'obseprof': 'ضعيف',
             'prenomnom': 'لينا بن عمر'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013074006166',
             'NOTEEPRE': '07.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '19',
             'obseprof': 'دون المتوسط',
             'prenomnom': 'ليندا عبد السلام'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013074006166',
             'NOTEEPRE': '06.50',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '19',
             'obseprof': 'دون المتوسط',
             'prenomnom': 'ليندا عبد السلام'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '013074006166',
             'NOTEEPRE': '10.25',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '19',
             'obseprof': 'دون المتوسط',
             'prenomnom': 'ليندا عبد السلام'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013005026941',
             'NOTEEPRE': '15.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '20',
             'obseprof': 'حسن',
             'prenomnom': 'محمد بشار خليفة الهميسي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013005026941',
             'NOTEEPRE': '14.50',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '20',
             'obseprof': 'حسن',
             'prenomnom': 'محمد بشار خليفة الهميسي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '013005026941',
             'NOTEEPRE': '14.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '20',
             'obseprof': 'حسن',
             'prenomnom': 'محمد بشار خليفة الهميسي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013081049376',
             'NOTEEPRE': '14.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '21',
             'obseprof': 'حسن',
             'prenomnom': 'محمد مهدي الزياني'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013081049376',
             'NOTEEPRE': '15.00',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '21',
             'obseprof': 'حسن',
             'prenomnom': 'محمد مهدي الزياني'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '013081049376',
             'NOTEEPRE': '14.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '21',
             'obseprof': 'حسن',
             'prenomnom': 'محمد مهدي الزياني'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012571008525',
             'NOTEEPRE': '07.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '22',
             'obseprof': 'متوسط',
             'prenomnom': 'محمد امين مسلم'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012571008525',
             'NOTEEPRE': '13.00',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '22',
             'obseprof': 'متوسط',
             'prenomnom': 'محمد امين مسلم'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012571008525',
             'NOTEEPRE': '09.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '22',
             'obseprof': 'متوسط',
             'prenomnom': 'محمد امين مسلم'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012786024684',
             'NOTEEPRE': '09.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '23',
             'obseprof': 'متوسط',
             'prenomnom': 'مريم حسيون'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012786024684',
             'NOTEEPRE': '10.50',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '23',
             'obseprof': 'متوسط',
             'prenomnom': 'مريم حسيون'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012786024684',
             'NOTEEPRE': '12.75',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '23',
             'obseprof': 'متوسط',
             'prenomnom': 'مريم حسيون'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013057009241',
             'NOTEEPRE': '13.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '24',
             'obseprof': 'حسن',
             'prenomnom': 'محمد مهدي الدواس'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013057009241',
             'NOTEEPRE': '15.75',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '24',
             'obseprof': 'حسن',
             'prenomnom': 'محمد مهدي الدواس'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '013057009241',
             'NOTEEPRE': '16.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '24',
             'obseprof': 'حسن',
             'prenomnom': 'محمد مهدي الدواس'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012466006530',
             'NOTEEPRE': '08.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '25',
             'obseprof': 'ضعيف',
             'prenomnom': 'محمد الهادي البجاوي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012466006530',
             'NOTEEPRE': '06.50',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '25',
             'obseprof': 'ضعيف',
             'prenomnom': 'محمد الهادي البجاوي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012466006530',
             'NOTEEPRE': '07.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '25',
             'obseprof': 'ضعيف',
             'prenomnom': 'محمد الهادي البجاوي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013118022443',
             'NOTEEPRE': '12.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '26',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'نور عبد الجليل'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013118022443',
             'NOTEEPRE': '14.00',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '26',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'نور عبد الجليل'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '013118022443',
             'NOTEEPRE': '12.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '26',
             'obseprof': 'قريب من الحسن',
             'prenomnom': 'نور عبد الجليل'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012862029642',
             'NOTEEPRE': '16.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '27',
             'obseprof': 'حسن جدا',
             'prenomnom': 'ياسين دحمان'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '012862029642',
             'NOTEEPRE': '18.25',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '27',
             'obseprof': 'حسن جدا',
             'prenomnom': 'ياسين دحمان'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '012862029642',
             'NOTEEPRE': '16.50',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '27',
             'obseprof': 'حسن جدا',
             'prenomnom': 'ياسين دحمان'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013083029085',
             'NOTEEPRE': '11.00',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض مــراقبة1',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '28',
             'obseprof': 'دون المتوسط',
             'prenomnom': 'يسري العيادي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '30',
             'CODETYPEMATI': '10',
             'IDENELEV': '013083029085',
             'NOTEEPRE': '09.50',
             'NUMEEPRE': '2',
             'libTypeEpr': 'فرض مــراقبة2',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '28',
             'obseprof': 'دون المتوسط',
             'prenomnom': 'يسري العيادي'},
            {'CODEETAB': '843010',
             'CODEMATI': '2003',
             'CODETYPEEPRE': '40',
             'CODETYPEMATI': '10',
             'IDENELEV': '013083029085',
             'NOTEEPRE': '09.25',
             'NUMEEPRE': '1',
             'libTypeEpr': 'فرض تأليفي',
             'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية',
             'numOrdre': '28',
             'obseprof': 'دون المتوسط',
             'prenomnom': 'يسري العيادي'}],
 'epreuves': [
    {'CODEETAB': '843010',
               'CODEMATI': '2003',
               'CODETYPEEPRE': '30',
               'CODETYPEMATI': '10',
               'NOTEEPRE': '--.--',
               'NUMEEPRE': '1',
               'abretypeeprear': 'ف.م.',
               'libTypeEpr': 'فرض مــراقبة1',
               'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية'},
              {'CODEETAB': '843010',
               'CODEMATI': '2003',
               'CODETYPEEPRE': '30',
               'CODETYPEMATI': '10',
               'NOTEEPRE': '--.--',
               'NUMEEPRE': '2',
               'abretypeeprear': 'ف.م.',
               'libTypeEpr': 'فرض مــراقبة2',
               'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية'},
              {'CODEETAB': '843010',
               'CODEMATI': '2003',
               'CODETYPEEPRE': '40',
               'CODETYPEMATI': '10',
               'NOTEEPRE': '--.--',
               'NUMEEPRE': '1',
               'abretypeeprear': 'ف.ت.',
               'libTypeEpr': 'فرض تأليفي',
               'libeMat': 'الأنظمة و تكنولوحيا المعلوماتية'}
               ],
 'generalInfos': {
    'codeclass': '31231301',
                  'codedisc': '20',
                  'codedre': '84',
                  'codeeetab': '843010',
                  'codematiere': '2003',
                  'codeperiodexam': '31',
                  'drear': 'ـسوسة',
                  'iuense': '0077143288',
                  'libeclass': 'ثالثة علوم إعلامية 1',
                  'libedisc': 'إعلامية',
                  'libeetab': 'معهد حمام سوسة',
                  'libematier': 'الأنظمة و تكنولوحيا المعلوماتية',
                  'libens': 'محمد أنيس ماني',
                  'libperiodexam': 'الثلاثي الأول',
                  'nbrEleve': '28',
                  'nbrclass': '2'
                  }
                  }
